include("runtests_setup.jl")

using Oceananigans
using Oceananigans: prognostic_state, restore_prognostic_state!
using Oceananigans.TimeSteppers: time_step!
using NumericalEarth.EarthSystemModels.InterfaceComputations:
    CanopyAirSpace, CanopyConductanceHumidity, CriticalSaturation, InteractiveAbsorbedPAR,
    SoilConductiveFlux, SoilSkinTemperature, DiagnosticSkin, PrognosticSkin,
    DiagnosticCanopyAir, PrognosticCanopyAir

checkpoint_test_cas(FT; storage) = CanopyAirSpace(FT;
    soil = bare_soil_humidity(FT),
    canopy = CanopyConductanceHumidity(FT; leaf_area_index = 4.0, moisture_stress = CriticalSaturation(0.5),
                                       absorbed_par = InteractiveAbsorbedPAR(FT)),
    soil_skin_flux = SoilConductiveFlux(1.5, 0.05), storage)

checkpoint_test_model(arch; temperature, humidity = temperature) =
    coupled_land_model(arch; atmosphere_land_interface_temperature = temperature,
                       atmosphere_land_interface_specific_humidity = humidity)

# Step `m1` forward, checkpoint it, restore into the freshly built `m2`, then step
# both together and require identical fluxes — the restored run must be
# indistinguishable from the uninterrupted one.
function roundtrip!(m1, m2; spinup = 6, continuation = 6, Δt = 300.0)
    for _ in 1:spinup
        time_step!(m1, Δt)
    end
    state = deepcopy(prognostic_state(m1))
    restore_prognostic_state!(m2, state)
    for _ in 1:continuation
        time_step!(m1, Δt)
        time_step!(m2, Δt)
    end
    f1 = m1.interfaces.atmosphere_land_interface.fluxes
    f2 = m2.interfaces.atmosphere_land_interface.fluxes
    return (scalar(f1.latent_heat), scalar(f1.sensible_heat)),
           (scalar(f2.latent_heat), scalar(f2.sensible_heat))
end

@testset "Prognostic interface state checkpointing" begin
    for arch in test_architectures
        # --- prognostic canopy air: the node state must survive the round trip.
        cas() = checkpoint_test_cas(Float64; storage = PrognosticCanopyAir())
        m1 = checkpoint_test_model(arch; temperature = cas())
        m2 = checkpoint_test_model(arch; temperature = cas())
        state = prognostic_state(m1)
        @test state.interfaces.atmosphere_land_interface !== nothing
        (LE1, H1), (LE2, H2) = roundtrip!(m1, m2)
        Ts1 = m1.interfaces.atmosphere_land_interface.temperature
        Ts2 = m2.interfaces.atmosphere_land_interface.temperature
        @test scalar(Ts2.state.temperature) ≈ scalar(Ts1.state.temperature)
        @test scalar(Ts2.state.specific_humidity) ≈ scalar(Ts1.state.specific_humidity)
        @test LE2 ≈ LE1
        @test H2 ≈ H1

        # --- prognostic skin: the interface-temperature field is the state.
        skin() = SoilSkinTemperature(1.5, 0.05; storage = PrognosticSkin(heat_capacity = 1e5))
        m1 = checkpoint_test_model(arch; temperature = skin(), humidity = bare_soil_humidity(Float64))
        m2 = checkpoint_test_model(arch; temperature = skin(), humidity = bare_soil_humidity(Float64))
        state = prognostic_state(m1)
        @test state.interfaces.atmosphere_land_interface !== nothing
        (LE1, H1), (LE2, H2) = roundtrip!(m1, m2)
        @test scalar(m2.interfaces.atmosphere_land_interface.temperature) ≈
              scalar(m1.interfaces.atmosphere_land_interface.temperature)
        @test LE2 ≈ LE1
        @test H2 ≈ H1

        # --- diagnostic formulations contribute no interface state (everything
        # they need is regenerated by the next update), yet still round-trip
        # exactly given the checkpointed slab forcing; and restoring an old
        # checkpoint without an interface entry is tolerated.
        cd() = checkpoint_test_cas(Float64; storage = DiagnosticCanopyAir())
        m1 = checkpoint_test_model(arch; temperature = cd())
        m2 = checkpoint_test_model(arch; temperature = cd())
        @test prognostic_state(m1).interfaces.atmosphere_land_interface === nothing
        (LE1, H1), (LE2, H2) = roundtrip!(m1, m2)
        @test LE2 ≈ LE1
        @test H2 ≈ H1
        @test restore_prognostic_state!(m2.interfaces, (;)) === m2.interfaces
    end
end
